export const GET_ALL_NOTES_REQUEST = 'GET_ALL_NOTES_REQUEST'
export const GET_ALL_NOTES_SUCCESS = 'GET_ALL_NOTES_SUCCESS'
export const GET_ALL_NOTES_FAIL = 'GET_ALL_NOTES_FAIL'

export const CREATE_NOTE_REQUEST = 'CREATE_NOTE_REQUEST'
export const CREATE_NOTE_SUCCESS = 'CREATE_NOTE_SUCCESS'
export const CREATE_NOTE_FAIL = 'CREATE_NOTE_FAIL'
